"""
artifact_factory.py — H6 ARTIFACT FACTORY (dependency-free builders)
====================================================================
Completion rule (constitutional): a mission is NOT complete until a usable
ARTIFACT exists. Collecting knowledge is not creating an asset. H4 decides WHAT
the artifact should be; this factory PHYSICALLY GENERATES it, verifies the file
exists, and returns the path for attachment to the mission ledger.

Builders (no third-party dependencies — runs anywhere Python runs):
  1. PDF Builder            — a valid multi-page PDF (hand-written, base-14 font)
  2. HTML Dashboard Builder — a self-contained interactive dashboard
  3. Knowledge Graph Builder— a self-contained inline-SVG knowledge graph (+JSON)
  4. Obsidian Vault Builder — linked markdown notes written into the vault

  build(asset_type, knowledge, out_dir) -> {ok, type, path, bytes, exists, error}

Deterministic, model-free. Note: the PDF base-14 font is Latin-1 only; non-Latin
text (e.g. Thai) is replaced with '?' in PDF — HTML / Obsidian / Graph render
full Unicode, and H4 routes most knowledge to those richer artifacts anyway.

License: Apache-2.0 — ElmatadorZ / THE HOUSE
"""
from __future__ import annotations

import html as _html
import json
import math
import re
import time
from pathlib import Path
from typing import Any, Dict, List, Optional

# H4 asset_type → builder
_BUILDER_FOR = {
    "PDF Report": "pdf", "Executive Brief": "pdf",
    "Interactive HTML Dashboard": "html", "Comparison Matrix": "html",
    "Knowledge Graph": "graph",
    "Obsidian Knowledge Base": "obsidian",
    "Markdown Note": "markdown",
}
_EXT = {"pdf": ".pdf", "html": ".html", "graph": ".html", "obsidian": ".md", "markdown": ".md"}


def choose_builder(asset_type: str) -> str:
    return _BUILDER_FOR.get(asset_type or "", "markdown")


def _slug(s: str, n: int = 48) -> str:
    s = re.sub(r"[^\w\- ]+", "", (s or "mission")).strip().replace(" ", "-").lower()
    return (s or "mission")[:n]


def assemble_knowledge(answer: Dict[str, Any], summary: str = "",
                       metrics: Optional[Dict[str, Any]] = None,
                       sources: Optional[List[str]] = None) -> Dict[str, Any]:
    """Build the factory's knowledge payload from a house_state answer()."""
    a = answer or {}
    return {
        "title": (a.get("question") or "Mission").strip()[:120],
        "mission": a.get("question", ""),
        "summary": (summary or "").strip(),
        "known": list(a.get("what_we_know") or []),
        "beliefs": [{"belief": b.get("belief", ""), "confidence": b.get("confidence", 0.0)}
                    for b in (a.get("what_we_believe") or []) if b.get("belief")],
        "unknowns": list(a.get("what_we_dont_know") or []),
        "assumptions": [h.get("hypothesis", "") for h in (a.get("hypotheses") or []) if h.get("hypothesis")],
        "sources": list(sources or []),
        "metrics": metrics or {},
    }


# ── 1. PDF BUILDER (hand-written, valid, multi-page) ─────────────────────────
def _pdf_escape(s: str) -> str:
    return s.replace("\\", r"\\").replace("(", r"\(").replace(")", r"\)")


def _latin1(s: str) -> str:
    return (s or "").encode("latin-1", "replace").decode("latin-1")


def _wrap(s: str, width: int = 95) -> List[str]:
    out: List[str] = []
    for raw in (s or "").splitlines() or [""]:
        if not raw:
            out.append("")
            continue
        while len(raw) > width:
            cut = raw.rfind(" ", 0, width)
            cut = cut if cut > 40 else width
            out.append(raw[:cut]); raw = raw[cut:].lstrip()
        out.append(raw)
    return out


def _knowledge_lines(k: Dict[str, Any]) -> List[str]:
    L = [k.get("title", "Mission"), "=" * 60, ""]
    if k.get("summary"):
        L += ["SUMMARY", "-------"] + _wrap(k["summary"]) + [""]
    if k.get("known"):
        L += ["WHAT WE KNOW", "------------"] + [f"  - {x}" for x in k["known"]] + [""]
    if k.get("beliefs"):
        L += ["BELIEFS", "-------"] + [f"  * {b['belief']}  ({int(float(b.get('confidence',0) or 0)*100)}%)" for b in k["beliefs"]] + [""]
    if k.get("assumptions"):
        L += ["ASSUMPTIONS", "-----------"] + [f"  ? {x}" for x in k["assumptions"]] + [""]
    if k.get("unknowns"):
        L += ["OPEN QUESTIONS", "--------------"] + [f"  ! {x}" for x in k["unknowns"]] + [""]
    m = k.get("metrics") or {}
    if m:
        L += ["FRONTIER METRICS", "----------------",
              f"  knowledge_debt={m.get('knowledge_debt','-')} coverage={m.get('coverage','-')} "
              f"known={m.get('known_count','-')}", ""]
    L += ["", f"Generated by THE HOUSE · Artifact Factory · {time.strftime('%Y-%m-%d %H:%M:%S')}"]
    # wrap everything to page width
    wrapped: List[str] = []
    for ln in L:
        wrapped += _wrap(ln) if len(ln) > 95 else [ln]
    return wrapped


def _build_pdf(k: Dict[str, Any], out_path: Path) -> None:
    lines = [_latin1(x) for x in _knowledge_lines(k)]
    PAGE_LINES = 52
    pages = [lines[i:i + PAGE_LINES] for i in range(0, len(lines), PAGE_LINES)] or [[""]]
    P = len(pages)
    font_obj = 3 + 2 * P
    parts: List[tuple] = []
    parts.append((1, b"<</Type/Catalog/Pages 2 0 R>>"))
    kids = " ".join(f"{3 + 2 * i} 0 R" for i in range(P))
    parts.append((2, f"<</Type/Pages/Kids[{kids}]/Count {P}>>".encode()))
    for i, page in enumerate(pages):
        pnum, cnum = 3 + 2 * i, 4 + 2 * i
        parts.append((pnum, (f"<</Type/Page/Parent 2 0 R/MediaBox[0 0 612 792]"
                             f"/Resources<</Font<</F1 {font_obj} 0 R>>>>/Contents {cnum} 0 R>>").encode()))
        body = ["BT /F1 10 Tf 50 750 Td 13 TL"]
        first = True
        for ln in page:
            esc = _pdf_escape(ln)[:230]
            body.append(f"({esc}) Tj" if first else f"T* ({esc}) Tj")
            first = False
        body.append("ET")
        stream = " ".join(body).encode("latin-1", "replace")
        parts.append((cnum, b"<</Length %d>>\nstream\n%s\nendstream" % (len(stream), stream)))
    parts.append((font_obj, b"<</Type/Font/Subtype/Type1/BaseFont/Helvetica/Encoding/WinAnsiEncoding>>"))

    out = b"%PDF-1.4\n"
    offsets: Dict[int, int] = {}
    for num, body in sorted(parts, key=lambda x: x[0]):
        offsets[num] = len(out)
        out += f"{num} 0 obj\n".encode() + body + b"\nendobj\n"
    xref_pos = len(out)
    n = len(parts) + 1
    out += f"xref\n0 {n}\n".encode() + b"0000000000 65535 f \n"
    for num in range(1, n):
        out += ("%010d 00000 n \n" % offsets[num]).encode()
    out += f"trailer\n<</Size {n}/Root 1 0 R>>\nstartxref\n{xref_pos}\n%%EOF".encode()
    out_path.write_bytes(out)


# ── 2. HTML DASHBOARD BUILDER ────────────────────────────────────────────────
def _e(s: Any) -> str:
    return _html.escape(str(s if s is not None else ""))


def _build_html(k: Dict[str, Any], out_path: Path) -> None:
    m = k.get("metrics") or {}
    def card(title, body): return f'<section class="card"><h2>{_e(title)}</h2>{body}</section>'
    def ul(items): return "<ul>" + "".join(f"<li>{_e(x)}</li>" for x in items) + "</ul>" if items else "<p class=dim>—</p>"
    beliefs = "".join(
        f'<div class="belief"><span>{_e(b["belief"])}</span>'
        f'<div class="bar"><i style="width:{int(float(b.get("confidence",0) or 0)*100)}%"></i></div>'
        f'<b>{int(float(b.get("confidence",0) or 0)*100)}%</b></div>'
        for b in k.get("beliefs", [])) or "<p class=dim>—</p>"
    metrics = "".join(f'<div class="metric"><b>{_e(v)}</b><span>{_e(kk)}</span></div>'
                      for kk, v in m.items()) or ""
    doc = f"""<!doctype html><html><head><meta charset="utf-8">
<title>{_e(k.get('title','Mission'))} — THE HOUSE</title><style>
:root{{--gold:#d4ac60;--ink:#e8e6e0;--dim:#8a8a8a;--bg:#13151a;--card:#1b1e25;--rule:#2a2d36}}
*{{box-sizing:border-box}}body{{margin:0;background:var(--bg);color:var(--ink);font:14px/1.5 system-ui,Segoe UI,sans-serif}}
header{{padding:26px 34px;border-bottom:1px solid var(--rule);background:linear-gradient(180deg,rgba(212,172,96,.07),transparent)}}
h1{{margin:0;font-size:22px;color:var(--gold);font-weight:600}}.sub{{color:var(--dim);font-size:12px;margin-top:4px}}
main{{padding:22px 34px;display:grid;grid-template-columns:repeat(auto-fit,minmax(320px,1fr));gap:16px;max-width:1400px}}
.card{{background:var(--card);border:1px solid var(--rule);border-radius:10px;padding:16px 18px}}
h2{{margin:0 0 10px;font-size:12px;letter-spacing:.16em;text-transform:uppercase;color:var(--gold)}}
ul{{margin:0;padding-left:18px}}li{{margin:3px 0}}.dim{{color:var(--dim)}}
.belief{{display:flex;align-items:center;gap:10px;margin:6px 0}}.belief span{{flex:1}}
.bar{{flex:0 0 90px;height:6px;background:#2a2d36;border-radius:4px;overflow:hidden}}
.bar>i{{display:block;height:100%;background:linear-gradient(90deg,#7a6a2a,var(--gold))}}
.metrics{{display:flex;gap:18px;flex-wrap:wrap}}.metric{{text-align:center}}.metric b{{display:block;font-size:22px;color:var(--gold)}}
.metric span{{font-size:10px;color:var(--dim);letter-spacing:.1em;text-transform:uppercase}}
footer{{padding:16px 34px;color:var(--dim);font-size:11px;border-top:1px solid var(--rule)}}
</style></head><body>
<header><h1>{_e(k.get('title','Mission'))}</h1><div class="sub">THE HOUSE · Knowledge Dashboard · {time.strftime('%Y-%m-%d %H:%M')}</div></header>
<main>
{card('Summary', f'<p>{_e(k.get("summary","")) or "<span class=dim>—</span>"}</p>')}
{card('Metrics', f'<div class="metrics">{metrics or "<span class=dim>—</span>"}</div>')}
{card('What We Know', ul(k.get('known',[])))}
{card('Beliefs', beliefs)}
{card('Assumptions', ul(k.get('assumptions',[])))}
{card('Open Questions', ul(k.get('unknowns',[])))}
{card('Sources', ul(k.get('sources',[])))}
</main>
<footer>Generated by THE HOUSE · Artifact Factory · a mission is not complete until a usable artifact exists.</footer>
</body></html>"""
    out_path.write_text(doc, encoding="utf-8")


# ── 3. KNOWLEDGE GRAPH BUILDER (inline SVG, self-contained) ──────────────────
def _build_graph(k: Dict[str, Any], out_path: Path) -> None:
    center = k.get("title", "Mission")
    nodes = (k.get("known", []) + [b["belief"] for b in k.get("beliefs", [])])[:14]
    W, H, cx, cy, R = 920, 640, 460, 330, 230
    svg = [f'<svg viewBox="0 0 {W} {H}" xmlns="http://www.w3.org/2000/svg" font-family="system-ui,sans-serif">']
    svg.append(f'<rect width="{W}" height="{H}" fill="#13151a"/>')
    pts = []
    for i, _ in enumerate(nodes):
        ang = (2 * math.pi * i / max(1, len(nodes))) - math.pi / 2
        pts.append((cx + R * math.cos(ang), cy + R * math.sin(ang)))
    for (x, y) in pts:
        svg.append(f'<line x1="{cx}" y1="{cy}" x2="{x:.0f}" y2="{y:.0f}" stroke="#3a3d46" stroke-width="1.5"/>')
    for (x, y), label in zip(pts, nodes):
        t = _e(label[:34])
        svg.append(f'<circle cx="{x:.0f}" cy="{y:.0f}" r="7" fill="#7da26a"/>')
        anchor = "start" if x >= cx else "end"
        dx = 12 if x >= cx else -12
        svg.append(f'<text x="{x+dx:.0f}" y="{y+4:.0f}" fill="#cfcfcf" font-size="12" text-anchor="{anchor}">{t}</text>')
    svg.append(f'<circle cx="{cx}" cy="{cy}" r="14" fill="#d4ac60"/>')
    svg.append(f'<text x="{cx}" y="{cy-22}" fill="#d4ac60" font-size="15" font-weight="700" text-anchor="middle">{_e(center[:48])}</text>')
    svg.append("</svg>")
    graph_json = {"center": center,
                  "nodes": [{"id": i, "label": l} for i, l in enumerate(nodes)],
                  "edges": [{"from": "center", "to": i} for i in range(len(nodes))]}
    doc = (f'<!doctype html><html><head><meta charset="utf-8"><title>{_e(center)} — Knowledge Graph</title>'
           '<style>body{margin:0;background:#13151a;color:#e8e6e0;font-family:system-ui,sans-serif}'
           'header{padding:20px 30px;color:#d4ac60;border-bottom:1px solid #2a2d36}'
           'pre{display:none}</style></head><body>'
           f'<header><b>{_e(center)}</b> — Knowledge Graph · THE HOUSE</header>'
           f'<div style="padding:20px">{"".join(svg)}</div>'
           f'<pre id="graph-data">{_e(json.dumps(graph_json))}</pre></body></html>')
    out_path.write_text(doc, encoding="utf-8")


# ── 4. OBSIDIAN VAULT BUILDER ────────────────────────────────────────────────
def _build_obsidian(k: Dict[str, Any], out_path: Path) -> Path:
    """Write a linked note set. out_path is the INDEX note; fact notes live in a
    sibling folder and are wiki-linked from the index."""
    folder = out_path.parent / (out_path.stem + "_notes")
    folder.mkdir(parents=True, exist_ok=True)
    title = k.get("title", "Mission")
    links = []
    for i, fact in enumerate(k.get("known", [])[:30]):
        nslug = _slug(fact, 40) or f"fact-{i}"
        note = folder / f"{nslug}.md"
        note.write_text(
            f"---\ntype: knowledge\nmission: \"{title}\"\nsource: THE HOUSE\n---\n\n"
            f"# {fact}\n\n> Captured for [[{title}]].\n",
            encoding="utf-8")
        links.append(f"- [[{nslug}|{fact[:60]}]]")
    body = [f"---\ntype: mission-index\ngenerated: {time.strftime('%Y-%m-%d %H:%M')}\nsource: THE HOUSE\n---\n",
            f"# {title}\n"]
    if k.get("summary"):
        body += ["## Summary", k["summary"], ""]
    if k.get("beliefs"):
        body += ["## Beliefs"] + [f"- {b['belief']} ({int(float(b.get('confidence',0) or 0)*100)}%)" for b in k["beliefs"]] + [""]
    body += ["## Known (linked notes)"] + (links or ["- _none_"]) + [""]
    if k.get("unknowns"):
        body += ["## Open Questions"] + [f"- {u}" for u in k["unknowns"]] + [""]
    out_path.write_text("\n".join(body), encoding="utf-8")
    return out_path


# ── dispatcher ───────────────────────────────────────────────────────────────
def build(asset_type: str, knowledge: Dict[str, Any], out_dir: str,
          base_name: str = "") -> Dict[str, Any]:
    """Physically generate the artifact. Returns path + existence proof."""
    kind = choose_builder(asset_type)
    try:
        d = Path(out_dir)
        d.mkdir(parents=True, exist_ok=True)
        stem = _slug(base_name or knowledge.get("title", "mission"))
        path = d / f"{stem}{_EXT[kind]}"
        if kind == "pdf":
            _build_pdf(knowledge, path)
        elif kind == "html":
            _build_html(knowledge, path)
        elif kind == "graph":
            _build_graph(knowledge, path)
        elif kind == "obsidian":
            path = _build_obsidian(knowledge, path)
        else:  # markdown
            path.write_text("# " + knowledge.get("title", "Mission") + "\n\n"
                            + (knowledge.get("summary", "") or "")
                            + "\n\n## Known\n" + "\n".join(f"- {x}" for x in knowledge.get("known", [])),
                            encoding="utf-8")
        exists = path.exists() and path.stat().st_size > 0
        return {"ok": exists, "type": asset_type, "builder": kind, "path": str(path),
                "bytes": path.stat().st_size if path.exists() else 0, "exists": exists,
                "error": "" if exists else "file not written"}
    except Exception as e:
        return {"ok": False, "type": asset_type, "builder": kind, "path": "",
                "bytes": 0, "exists": False, "error": str(e)}


def verify(path: str) -> bool:
    try:
        p = Path(path)
        return p.exists() and p.stat().st_size > 0
    except Exception:
        return False
