"""
openclaw_port.py
================
SkynetClaw <- OpenClaw — Tier 1 ports of OpenClaw infrastructure patterns.

Provides 4 independent utilities, each gracefully degradable:

    1. write_daily_diary(...)  — append a session summary to memory/YYYY-MM-DD.md
    2. TrajectoryWriter(...)   — emit per-run trajectory.jsonl alongside chat
    3. workspace_git_commit(...) — auto git init + commit on workspace writes
    4. ExecApprovals           — persistent record of irreversible-call approvals

Wire-in (in main.py agent_run, near the existing meta calls):

    from openclaw_port import (
        write_daily_diary, TrajectoryWriter, workspace_git_commit, ExecApprovals,
    )

Each utility is best-effort: any failure is caught, logged, and never breaks
the agent loop.

License: Apache-2.0 — ElmatadorZ
"""
from __future__ import annotations

import json
import os
import re
import time
import hashlib
import subprocess
import datetime as _dt
from pathlib import Path
from typing import Any, Dict, List, Optional

_BASE = Path(__file__).parent

# ──────────────────────────────────────────────────────────────────────────────
# 1. DAILY DIARY  —  memory/YYYY-MM-DD.md  (port of OpenClaw memory/ pattern)
# ──────────────────────────────────────────────────────────────────────────────
DIARY_DIR = _BASE / "memory"


def _safe_iso_date(tz_offset_hours: int = 7) -> str:
    """ISO date in user's local TZ (default Bangkok = UTC+7)."""
    now = _dt.datetime.now(_dt.timezone.utc) + _dt.timedelta(hours=tz_offset_hours)
    return now.date().isoformat()


def write_daily_diary(
    session_id: str,
    task: str,
    summary: str,
    tools_used: List[str],
    n_steps: int,
    status: str,                           # "TASK_COMPLETE" | "stuck" | "limit" | "error"
    duration_sec: float = 0.0,
    blocked_calls: int = 0,
) -> Optional[Path]:
    """
    Append one session entry to memory/YYYY-MM-DD.md.
    Returns the path written, or None on failure (never raises).
    """
    try:
        DIARY_DIR.mkdir(parents=True, exist_ok=True)
        date_str = _safe_iso_date()
        path = DIARY_DIR / f"{date_str}.md"
        ts_local = _dt.datetime.now().strftime("%H:%M:%S")
        # Top-of-file header (only on first entry of the day)
        if not path.exists():
            path.write_text(
                f"# Daily memory — {date_str}\n\n"
                f"_Auto-generated by SkynetClaw agent_run sessions._\n\n",
                encoding="utf-8",
            )
        emoji = {"TASK_COMPLETE":"✓", "stuck":"⚠", "limit":"⏱", "error":"✗"}.get(status, "·")
        # Trim noise from tools_used (deduplicate, keep order, limit to 10)
        seen = set(); tu_clean = []
        for t in tools_used:
            tn = t.split(":",1)[0].split("#",1)[0].strip()
            if tn and tn not in seen:
                seen.add(tn); tu_clean.append(tn)
        tu_clean = tu_clean[:10]
        entry = (
            f"---\n\n"
            f"## {emoji} {ts_local} — `{session_id}` · status={status}\n\n"
            f"**Task** (excerpt): {task[:300].strip()}\n\n"
            f"**Steps**: {n_steps} · **Tools**: {', '.join(tu_clean) or '(none)'} "
            f"· **Blocked**: {blocked_calls} · **Duration**: {duration_sec:.1f}s\n\n"
            f"**Summary**: {summary[:600].strip()}\n\n"
        )
        with path.open("a", encoding="utf-8") as f:
            f.write(entry)
        return path
    except Exception as e:
        print(f"[openclaw_port.diary] failed: {e}")
        return None


# ──────────────────────────────────────────────────────────────────────────────
# 2. TRAJECTORY WRITER — per-run JSONL log of tool calls + verdicts
#    (port of OpenClaw .trajectory.jsonl pattern)
# ──────────────────────────────────────────────────────────────────────────────
SESSIONS_DIR = _BASE / "sessions"


class TrajectoryWriter:
    """
    Write a single trajectory.jsonl file per agent_run.
    Each line is one event (start, step, tool_call, tool_result, gate_block,
    user_ask, complete, etc.) — replay-able, queryable, diffable.
    """

    def __init__(self, session_id: str, task: str = "", model: str = ""):
        self.session_id = session_id
        self.path: Optional[Path] = None
        self._fh = None
        self._t0 = time.time()
        self._step_count = 0
        try:
            SESSIONS_DIR.mkdir(parents=True, exist_ok=True)
            # Filename: {YYYYMMDD-HHMMSS}_{shortid}.trajectory.jsonl
            stamp = _dt.datetime.now().strftime("%Y%m%d-%H%M%S")
            short = session_id[:10] if session_id else hashlib.sha1(
                f"{stamp}{task}".encode()).hexdigest()[:10]
            self.path = SESSIONS_DIR / f"{stamp}_{short}.trajectory.jsonl"
            self._fh = self.path.open("w", encoding="utf-8")
            self._emit("session_start", {
                "session_id": session_id,
                "task_preview": (task or "")[:300],
                "model": model,
                "started_at": self._t0,
            })
        except Exception as e:
            print(f"[trajectory] init failed: {e}")
            self._fh = None
            self.path = None

    def _emit(self, event: str, payload: Dict[str, Any]) -> None:
        if self._fh is None:
            return
        try:
            line = {
                "ts": time.time(),
                "elapsed_ms": int((time.time() - self._t0) * 1000),
                "event": event,
                **payload,
            }
            self._fh.write(json.dumps(line, ensure_ascii=False, default=str) + "\n")
            self._fh.flush()
        except Exception:
            pass

    # Public events — call these from agent_run
    def step_begin(self, step_num: int) -> None:
        self._step_count = step_num
        self._emit("step", {"step": step_num})

    def plan_captured(self, plan: str) -> None:
        self._emit("plan", {"plan": plan[:600]})

    def tool_call(self, name: str, args: Dict[str, Any]) -> None:
        # Keep args compact — drop large content fields for readability
        compact = {}
        for k, v in (args or {}).items():
            if isinstance(v, str) and len(v) > 200:
                compact[k] = v[:200] + f"…(+{len(v)-200} chars)"
            else:
                compact[k] = v
        self._emit("tool_call", {
            "step": self._step_count, "name": name, "args": compact,
        })

    def tool_result(self, name: str, result: str, ok: bool = True) -> None:
        self._emit("tool_result", {
            "step": self._step_count, "name": name, "ok": ok,
            "preview": (result or "")[:400],
            "result_len": len(result or ""),
        })

    def gate_block(self, name: str, reason: str, kind: str = "shadow_gate") -> None:
        self._emit("gate_block", {
            "step": self._step_count, "name": name, "reason": reason[:300], "kind": kind,
        })

    def user_ask(self, question: str, options: List[str]) -> None:
        self._emit("user_ask", {
            "step": self._step_count,
            "question": question[:300],
            "options": options[:6],
        })

    def complete(self, status: str, summary: str = "") -> None:
        self._emit("complete", {
            "status": status,
            "summary": (summary or "")[:600],
            "total_ms": int((time.time() - self._t0) * 1000),
            "n_steps": self._step_count,
        })

    def close(self) -> None:
        try:
            if self._fh:
                self._fh.close()
                self._fh = None
        except Exception:
            pass


# ──────────────────────────────────────────────────────────────────────────────
# 3. WORKSPACE AUTO-GIT  —  init + commit after every successful write_file
#    (port of OpenClaw workspace/.git pattern)
# ──────────────────────────────────────────────────────────────────────────────
def _run(cmd: List[str], cwd: Path, timeout: int = 8) -> tuple:
    """Run a shell cmd; returns (rc, stdout, stderr). Best-effort."""
    try:
        r = subprocess.run(cmd, cwd=str(cwd), capture_output=True, text=True,
                           timeout=timeout)
        return r.returncode, r.stdout or "", r.stderr or ""
    except Exception as e:
        return -1, "", str(e)


def workspace_git_commit(
    workspace_path: str,
    message: str,
    author_name: str = "SkynetClaw",
    author_email: str = "skynet@elmatadorz.local",
) -> Dict[str, Any]:
    """
    Ensure workspace_path is a git repo (init if not), then `git add -A` +
    `git commit -m message`. Returns {ok, action, hash?, error?}.

    Best-effort: never raises. If git is missing or path doesn't exist, returns
    {ok: False, error: ...}.
    """
    out: Dict[str, Any] = {"ok": False, "action": "skipped"}
    if not workspace_path:
        out["error"] = "no workspace_path"; return out
    wp = Path(workspace_path)
    if not wp.exists() or not wp.is_dir():
        out["error"] = f"workspace not a directory: {wp}"; return out

    # Skip if user explicitly opted out via marker
    if (wp / ".no-skynet-git").exists():
        out["action"] = "skipped (user opt-out marker present)"; return out

    # Init if needed
    git_dir = wp / ".git"
    if not git_dir.exists():
        rc, _so, se = _run(["git", "init", "-q"], wp)
        if rc != 0:
            out["error"] = f"git init failed: {se[:200]}"; return out
        # Set local user (avoids global config issues)
        _run(["git", "config", "user.name",  author_name],  wp)
        _run(["git", "config", "user.email", author_email], wp)
        # Reasonable default ignores so we don't snapshot huge artifacts
        gi = wp / ".gitignore"
        if not gi.exists():
            try:
                gi.write_text(
                    "# Auto-generated by SkynetClaw\n"
                    "node_modules/\n__pycache__/\n*.pyc\n"
                    ".venv/\n.env\nvenv/\nbuild/\ndist/\n"
                    "*.log\n*.tmp\n*.bak\n.DS_Store\n",
                    encoding="utf-8",
                )
            except Exception:
                pass

    # Stage everything
    rc, _so, se = _run(["git", "add", "-A"], wp)
    if rc != 0:
        out["error"] = f"git add failed: {se[:200]}"; return out

    # Check if anything is staged
    rc_s, so_s, _ = _run(["git", "diff", "--cached", "--name-only"], wp)
    if not so_s.strip():
        out["action"] = "no-op (nothing to commit)"; out["ok"] = True; return out

    # Commit
    safe_msg = (message or "skynetclaw: workspace update")[:200]
    rc, _so, se = _run(
        ["git", "commit", "-q", "--no-verify",
         "-m", safe_msg,
         "--author", f"{author_name} <{author_email}>"],
        wp,
    )
    if rc != 0:
        out["error"] = f"git commit failed: {se[:200]}"; return out

    # Capture hash
    rc, so, _ = _run(["git", "rev-parse", "--short", "HEAD"], wp)
    if rc == 0 and so.strip():
        out["hash"] = so.strip()
    out["ok"] = True
    out["action"] = "committed"
    return out


# ──────────────────────────────────────────────────────────────────────────────
# 4. EXEC APPROVALS  —  persistent record of user decisions on irreversible calls
#    (port of OpenClaw exec-approvals.json pattern)
# ──────────────────────────────────────────────────────────────────────────────
APPROVALS_PATH = _BASE / "exec_approvals.json"


class ExecApprovals:
    """
    Tracks user decisions about irreversible operations across sessions.

    Schema:
      {
        "version": 1,
        "approvals": [
          {
            "id": "approval_<sha1>",
            "tool": "shell_command",
            "pattern": "rm -rf D:\\\\Skynet_Bridge\\\\*",
            "decision": "ALWAYS" | "DENY",
            "scope": "exact" | "prefix" | "regex",
            "first_decided": <ts>,
            "last_used": <ts>,
            "use_count": <int>
          }
        ]
      }

    `check(tool, args)` returns one of:
       "ALLOW"  — user previously approved (skip Shadow Gate prompt)
       "DENY"   — user previously denied (block immediately)
       None     — no decision recorded (Shadow Gate proceeds normally)
    """

    def __init__(self, path: Optional[Path] = None):
        self.path = path or APPROVALS_PATH
        self._data = self._load()

    # ── I/O ────────────────────────────────────────────────────────────────
    def _load(self) -> Dict[str, Any]:
        if not self.path.exists():
            return {"version": 1, "approvals": []}
        try:
            return json.loads(self.path.read_text(encoding="utf-8"))
        except Exception:
            return {"version": 1, "approvals": []}

    def _save(self) -> None:
        try:
            tmp = self.path.with_suffix(".tmp")
            tmp.write_text(json.dumps(self._data, ensure_ascii=False, indent=2),
                           encoding="utf-8")
            tmp.replace(self.path)
        except Exception as e:
            print(f"[exec_approvals] save failed: {e}")

    # ── Pattern matching ───────────────────────────────────────────────────
    @staticmethod
    def _summary(tool: str, args: Dict[str, Any]) -> str:
        """A stable, readable summary of a tool call (used for matching)."""
        parts = [tool]
        for k in ("path", "command", "code", "url", "name", "source", "destination"):
            v = (args or {}).get(k)
            if v:
                parts.append(f"{k}={str(v)[:200]}"); break
        return " ".join(parts)

    def _match(self, entry: Dict[str, Any], tool: str, args: Dict[str, Any]) -> bool:
        if entry.get("tool") and entry["tool"] != tool:
            return False
        scope = entry.get("scope", "exact")
        target = self._summary(tool, args)
        pat = entry.get("pattern", "")
        if not pat:
            return False
        if scope == "exact":
            return target == pat
        if scope == "prefix":
            return target.startswith(pat)
        if scope == "regex":
            try:
                return re.search(pat, target) is not None
            except re.error:
                return False
        return False

    # ── Public API ─────────────────────────────────────────────────────────
    def check(self, tool: str, args: Dict[str, Any]) -> Optional[str]:
        for e in self._data.get("approvals", []):
            if self._match(e, tool, args):
                e["last_used"] = time.time()
                e["use_count"] = int(e.get("use_count", 0)) + 1
                self._save()
                return e.get("decision")
        return None

    def record(self, tool: str, args: Dict[str, Any], decision: str,
               scope: str = "exact", note: str = "") -> Dict[str, Any]:
        """Record a user decision. decision must be 'ALWAYS' or 'DENY'."""
        if decision not in ("ALWAYS", "DENY"):
            raise ValueError("decision must be ALWAYS or DENY")
        target = self._summary(tool, args)
        eid = "approval_" + hashlib.sha1(
            f"{tool}|{target}|{scope}".encode()).hexdigest()[:10]
        # Update if exists
        for e in self._data.get("approvals", []):
            if e.get("id") == eid:
                e["decision"] = decision
                e["last_used"] = time.time()
                e["use_count"] = int(e.get("use_count", 0)) + 1
                if note: e["note"] = note
                self._save()
                return e
        entry = {
            "id": eid, "tool": tool, "pattern": target, "scope": scope,
            "decision": decision, "first_decided": time.time(),
            "last_used": time.time(), "use_count": 1,
        }
        if note: entry["note"] = note
        self._data.setdefault("approvals", []).append(entry)
        self._save()
        return entry

    def list_all(self) -> List[Dict[str, Any]]:
        return list(self._data.get("approvals", []))

    def revoke(self, approval_id: str) -> bool:
        before = len(self._data.get("approvals", []))
        self._data["approvals"] = [
            e for e in self._data.get("approvals", []) if e.get("id") != approval_id
        ]
        self._save()
        return len(self._data["approvals"]) < before


# ──────────────────────────────────────────────────────────────────────────────
# Self-test  —  python openclaw_port.py
# ──────────────────────────────────────────────────────────────────────────────
if __name__ == "__main__":
    import sys, tempfile
    try:
        sys.stdout.reconfigure(encoding="utf-8")
    except Exception:
        pass

    print("=== openclaw_port self-test ===\n")

    # 1. Daily diary
    p = write_daily_diary(
        session_id="test_abc123",
        task="ทดสอบเขียน diary จากการสร้าง telegram bot",
        summary="สร้าง folder, write_file 3 ครั้ง, install requirements, รัน bot ผ่าน",
        tools_used=["create_folder", "write_file", "write_file", "install_package", "run_python"],
        n_steps=5, status="TASK_COMPLETE", duration_sec=42.7, blocked_calls=0,
    )
    print(f"[1] daily diary written: {p}")

    # 2. TrajectoryWriter
    tw = TrajectoryWriter(session_id="test_traj_001", task="sample task", model="nemotron3:33b")
    tw.step_begin(1)
    tw.plan_captured("1) create_folder | 2) write_file | 3) shell")
    tw.tool_call("create_folder", {"path": "D:\\Test"})
    tw.tool_result("create_folder", "Created", ok=True)
    tw.gate_block("write_file", "VALUE-MATCH FAILED — fake gold price", kind="shadow_gate")
    tw.complete("TASK_COMPLETE", "ทำงานเสร็จ verify ผ่าน")
    tw.close()
    print(f"[2] trajectory written: {tw.path}")

    # 3. Workspace git (tmp dir)
    with tempfile.TemporaryDirectory() as tmp:
        # Drop a marker file
        (Path(tmp) / "hello.txt").write_text("hello world")
        r = workspace_git_commit(tmp, "first commit by self-test")
        print(f"[3] git commit: {r}")
        # Second commit (no changes -> no-op)
        r2 = workspace_git_commit(tmp, "second")
        print(f"    second call: {r2}")
        # Add another file
        (Path(tmp) / "world.txt").write_text("hello")
        r3 = workspace_git_commit(tmp, "add world.txt")
        print(f"    third call: {r3}")

    # 4. Exec approvals
    with tempfile.TemporaryDirectory() as tmp:
        ea = ExecApprovals(path=Path(tmp) / "approvals.json")
        # No prior decision
        d = ea.check("shell_command", {"command": "rm -rf D:\\Skynet_Bridge\\old"})
        print(f"[4] approval check (none):    {d}")
        # Record an ALLOW
        e = ea.record("shell_command", {"command": "rm -rf D:\\Skynet_Bridge\\old"},
                      decision="ALWAYS", scope="exact", note="bot cleanup")
        print(f"    recorded id: {e['id']}")
        # Re-check — should match
        d2 = ea.check("shell_command", {"command": "rm -rf D:\\Skynet_Bridge\\old"})
        print(f"    approval check (recorded): {d2}")
        # Different command — no match
        d3 = ea.check("shell_command", {"command": "rm -rf C:\\Windows"})
        print(f"    different command:         {d3}")
        # List & revoke
        print(f"    list: {len(ea.list_all())} entry")
        ea.revoke(e["id"])
        d4 = ea.check("shell_command", {"command": "rm -rf D:\\Skynet_Bridge\\old"})
        print(f"    after revoke:              {d4}")

    print("\n=== self-test OK ===")
